-- table t_walrus_task
CREATE TABLE `t_walrus_task` (
  `f_task_id` int(11) NOT NULL AUTO_INCREMENT,
  `f_author` varchar(100) NOT NULL COMMENT '任务提交人',
  `f_level` varchar(10) DEFAULT NULL COMMENT 'online|offline',
  `f_format` varchar(10) DEFAULT NULL COMMENT '任务提交格式：json|sql...',
  `f_desc` varchar(200) DEFAULT NULL COMMENT '任务描述',
  `f_type` varchar(30) DEFAULT NULL COMMENT '任务类型：spark...',
  `f_time_start` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `f_time_end` timestamp NOT NULL DEFAULT '1997-01-01 00:00:00',
  `f_logic` text DEFAULT NULL COMMENT '任务逻辑',
  `f_table` varchar(200) DEFAULT NULL COMMENT '查询表',
  `f_bday` varchar(100) DEFAULT NULL COMMENT '查询开始日期',
  `f_eday` varchar(100) DEFAULT NULL COMMENT '查询结束日期',
  `f_status` tinyint(4) NOT NULL DEFAULT 0,
  `f_save_mode` varchar(100) DEFAULT NULL COMMENT '保存方式',
  `f_save_format` varchar(100) DEFAULT NULL COMMENT '保存格式',
  `f_save_path` text DEFAULT NULL COMMENT '保存信息',
  `f_result_schema` varchar(500) DEFAULT NULL ,
  `f_result_lines` bigint(20) DEFAULT NULL COMMENT '结果行数',
  `f_error_code` tinyint(4) DEFAULT NULL COMMENT '错误码',
  `f_message` text DEFAULT NULL COMMENT '错误信息',
  `f_ext` text DEFAULT NULL,
  `f_resource` text DEFAULT NULL COMMENT 'spark任务资源',
  `f_parameter` text DEFAULT NULL COMMENT 'spark参数',
  `f_submit_type` varchar(50) DEFAULT NULL COMMENT '任务提交方式: local|thrift',
  `f_plan` text COMMENT '任务计划',
  PRIMARY KEY (`f_task_id`)
) ENGINE=InnoDB AUTO_INCREMENT=10000 DEFAULT CHARSET=utf8
